pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'virendranawkar'
        FRONTEND_IMAGE = "${DOCKERHUB_USER}/devops-frontend"
        BACKEND_IMAGE  = "${DOCKERHUB_USER}/devops-backend"
        K8S_DIR        = 'devops-test-suite/k8s'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('devops-test-suite/frontend') {
                    sh "docker build -t ${FRONTEND_IMAGE}:${BUILD_NUMBER} -t ${FRONTEND_IMAGE}:latest ."
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('devops-test-suite/backend') {
                    sh "docker build -t ${BACKEND_IMAGE}:${BUILD_NUMBER} -t ${BACKEND_IMAGE}:latest ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                    sh "docker push ${FRONTEND_IMAGE}:${BUILD_NUMBER}"
                    sh "docker push ${FRONTEND_IMAGE}:latest"
                    sh "docker push ${BACKEND_IMAGE}:${BUILD_NUMBER}"
                    sh "docker push ${BACKEND_IMAGE}:latest"
                }
            }
        }

        stage('Deploy to AKS') {
            steps {
                    sh "kubectl apply -f ${K8S_DIR}/namespace.yaml"
                    sh "kubectl apply -f ${K8S_DIR}/backend-deployment.yaml"
                    sh "kubectl apply -f ${K8S_DIR}/frontend-deployment.yaml"
                    sh "kubectl apply -f ${K8S_DIR}/hpa.yaml"
                    sh "kubectl apply -f ${K8S_DIR}/ingress.yaml"
                    sh "kubectl rollout restart deployment/frontend -n devops-dashboard"   // ← ADD THIS
                    sh "kubectl rollout restart deployment/backend -n devops-dashboard"    // ← ADD THIS
                    sh "kubectl rollout status deployment/backend -n devops-dashboard"
                    sh "kubectl rollout status deployment/frontend -n devops-dashboard"
                }
        }

    }

    post {
        success {
            echo '✅ Pipeline SUCCESS — App deployed to AKS!'
        }
        failure {
            echo '❌ Pipeline FAILED — Check logs above!'
        }
    }
}
